[mypy]
plugins = pydantic.mypy

show_error_codes = true
follow_imports = silent
strict_optional = true
warn_redundant_casts = True
warn_unused_ignores = True
disallow_any_generics = True
check_untyped_defs = True
no_implicit_reexport = True
warn_unused_configs = True
disallow_subclassing_any = False
disallow_incomplete_defs = True
ignore_missing_imports = True
disallow_untyped_defs = True

[pydantic-mypy]
init_forbid_extra = True
init_typed = True
warn_required_dynamic_aliases = True
warn_untyped_fields = True
