version: "3.9"

x-postgresql-db: &postgresql-db
  image: postgresql:14.1
  restart: always
  logging:
    driver: none
  environment:
      - POSTGRESQL_USER=user
      - POSTGRESQL_PASSWORD=mysqlpwd
      - POSTGRESQL_DB=accounting-db

services:
  db:
    <<: *postgresql-db
    ports:
      - "5432:5432"
    volumes:
      - postgresql_account_volume:/var/lib/postgresql/data/

volumes:
  postgresql_account_volume:
