version: "3.9"

x-postgresql-db: &postgresql-db
  image: postgres:14.1
  restart: always
  environment:
    - POSTGRES_USER=user
    - POSTGRES_PASSWORD=mysqlpwd
    - POSTGRES_DB=accounting-db

services:
  db:
    <<: *postgresql-db
    ports:
      - "5435:5432"
