version: "3.9"

x-mysql-db: &mysql-db
  image: mysql:5.6
  restart: always
  platform: linux/amd64
  logging:
    driver: none
  environment:
      - MYSQL_USER=user
      - MYSQL_PASSWORD=mysqlpwd
      - MYSQL_DATABASE=auth-db
      - MYSQL_ROOT_PASSWORD=mysqlpwd

services:

  mysql_dbl:
    <<: *mysql-db
    ports:
      - "5506:3306"
    volumes:
      - mysql_dbl_volume:/var/lib/mysql

volumes:
  mysql_dbl_volume:
